<Project>
    <Target
            Name="RemoveWindowsAppSDKPayloadFilesFromDesignTimeBuild"
            AfterTargets="AddMicrosoftWindowsAppSDKPayloadFilesFromComponents"
            Condition="'$(DesignTimeBuild)' == 'true' and '$(EnableMsixTooling)' == 'true'">
        <ItemGroup>
            <None Remove="@(MicrosoftWindowsAppSDKFiles)"/>
        </ItemGroup>
    </Target>
</Project>
