<Project>
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14.0</LangVersion>
        <Features>strict</Features>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <WarningLevel>10</WarningLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <NoWarn>$(NoWarn);IDE0005;MA0048</NoWarn>
    </PropertyGroup>
</Project>
