<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <Platforms>x86;x64;arm64;AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CsWin32RunAsBuildTask>true</CsWin32RunAsBuildTask>
        <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="CsToml"/>
        <PackageReference Include="CsToml.Generator">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="DotNext"/>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="Microsoft.Extensions.Options"/>
        <PackageReference Include="Microsoft.Windows.CsWin32">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Enrichers.Thread"/>
        <PackageReference Include="Serilog.Extensions.Hosting"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
        <PackageReference Include="Serilog.Sinks.Debug"/>
        <PackageReference Include="Serilog.Sinks.File"/>
    </ItemGroup>
    <ItemGroup>
        <AdditionalFiles Include="Interop\NativeMethods.txt"/>
    </ItemGroup>
</Project>
